# Generated by Django 4.2 on 2023-06-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consumible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.CharField(max_length=50)),
                ("cantidad", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Herramienta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("rastreo", models.IntegerField()),
                ("calibracion", models.DateField()),
                ("operario", models.CharField(max_length=40)),
                ("descipcion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Lider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("legajo", models.IntegerField()),
                ("sector", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Operario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("legajo", models.IntegerField()),
                ("lider", models.CharField(max_length=40)),
                ("funcion", models.TextField()),
            ],
        ),
    ]
