# Generated by Django 4.2 on 2023-06-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taller", "0007_remove_operario_lider_operario_lideres"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operario",
            name="lideres",
        ),
        migrations.AddField(
            model_name="operario",
            name="lider",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
