# Generated by Django 4.2 on 2023-06-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taller", "0008_remove_operario_lideres_operario_lider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lider",
            name="nombre",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="operario",
            name="lider",
            field=models.CharField(max_length=50),
        ),
    ]
