# Generated by Django 4.2 on 2023-06-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taller", "0009_alter_lider_nombre_alter_operario_lider"),
    ]

    operations = [
        migrations.AddField(
            model_name="operario",
            name="descripcion",
            field=models.TextField(default="descripción adicional"),
        ),
    ]
