# Generated by Django 4.2 on 2023-06-13 00:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taller", "0011_consumible_unidad"),
    ]

    operations = [
        migrations.RenameField(
            model_name="herramienta",
            old_name="descipcion",
            new_name="descripcion",
        ),
    ]
